name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    # Can not run the app - since it uses ratatui
    # - name: Run app sequential
    #   run: cargo run --verbose -j1 || cat gpu_info.txt
    # - name: Run app multithreaded
    #   run: cargo run --verbose -j 16 || cat gpu_info.txt
